version: '3'

includes:
  openapi:
    taskfile: taskfiles/OpenAPI.yml
  db:
    taskfile: taskfiles/Database.yml
  api:
    taskfile: taskfiles/API.yml
  dart:
    taskfile: taskfiles/Dart.yml
  flutter:
    taskfile: taskfiles/Flutter.yml
  verify:
    taskfile: taskfiles/Verify.yml
    flatten: true

tasks:
  default:
    desc: 利用可能なタスクを表示する
    cmds:
      - task --list
